Modified `get_storage_at` procedures for v5
vulcanize/ipld-eth-db pull request #127
Opened 2023-03-08 00:45 UTC by i-norden

For https://github.com/cerc-io/ipld-eth-statedb/issues/6 and ipld-eth-server 

Modified procedures from https://github.com/cerc-io/ipld-eth-db/blob/v4/db/migrations/00023_get_storage_at_functions.sql#L16

Differences are that
1. We no longer need to first search for the `path` corresponding to a `leaf_key`.
2. We can return the value directly, preventing a second trip to or JOIN on `ipld.blocks` (unless we need the full IPLD object, the full leaf node, not just the value it stores).
3. When the optimistic search doesn't work (it returns a non-canonical result), we now only have to JOIN between `header_cids` and `storage_cids`, not all three of `header_cids`, `storage_cids`, and `state_cids`.

As alluded to above, it still splits the search into an optimistic first pass and a fallback option that checks for canonicity by joining on `header_cids` and calling the `canonical_header_hash()` stored procedure. Perhaps this is unnecessary now that in the pessimistic path we only join between `header_cids` and `storage_cids`? We can test this further once we have a  size and complexity representative v5 database to do so on.

2023-03-08 09:27 UTC, roysc requested changes
One fix needed

2023-03-08 09:27 UTC, roysc commented on db/migrations/00016_create_stored_procedures.sql
> +-- returns if the state leaf key is vacated (previously existed but now is empty) at the provided block hash
```suggestion
-- returns whether the state leaf key is vacated (previously existed but now is empty) at the provided block hash
```

2023-03-08 09:27 UTC, roysc commented on db/migrations/00016_create_stored_procedures.sql
> +-- returns if the state leaf key is vacated (previously existed but now is empty) at the provided block height
```suggestion
-- returns whether the state leaf key is vacated (previously existed but now is empty) at the provided block height
```

2023-03-08 09:27 UTC, roysc commented on db/migrations/00016_create_stored_procedures.sql
> +CREATE OR REPLACE FUNCTION was_state_leaf_removed(v_key VARCHAR(66), v_hash VARCHAR)
This could also be defined in terms of `was_state_leaf_removed_by_number` couldn't it?

2023-03-08 09:27 UTC, roysc commented on db/migrations/00016_create_stored_procedures.sql
> +CREATE OR REPLACE FUNCTION was_state_leaf_removed(v_key VARCHAR(66), v_hash VARCHAR)
Tangential question: why do we store hashes as var char rather than `bytea`? is it because there is no fixed-length byte array?

2023-03-08 09:27 UTC, roysc commented on db/migrations/00017_create_get_storage_at_functions.sql
> +                AND state_cids.block_number = header_cids.block_number
Should be `storage_cids` here

2023-03-08 09:27 UTC, roysc commented on db/migrations/00017_create_get_storage_at_functions.sql
> +    END IF;
Is this just a short-circuit? the next function call should return null anyway right?

2023-03-08 16:13 UTC, i-norden commented on db/migrations/00016_create_stored_procedures.sql
> +CREATE OR REPLACE FUNCTION was_state_leaf_removed(v_key VARCHAR(66), v_hash VARCHAR)
Yeah and I'm not sure we need it at all anymore tbh

2023-03-08 16:13 UTC, i-norden commented on db/migrations/00017_create_get_storage_at_functions.sql
> +                AND state_cids.block_number = header_cids.block_number
Thanks, great catch, this means we are missing another test case too as this path isnt being tested

2023-03-08 16:13 UTC, i-norden commented on db/migrations/00017_create_get_storage_at_functions.sql
> +    END IF;
Yeah its just a short-circuit

2023-03-08 16:23 UTC, i-norden commented on db/migrations/00016_create_stored_procedures.sql
> +CREATE OR REPLACE FUNCTION was_state_leaf_removed(v_key VARCHAR(66), v_hash VARCHAR)
It's sort of arbitrary, due to a collection of small reasons, nothing major.

1. This was how it was defined years ago in the origianl vulcanizedb, legacy carried over
2. In terms of text/varchar vs bytea the reason is that the text/varchar string representation is the human readable format and the format for addresses/hashes that you see passed around just about anywhere. Aka it is the  most commonly expected representation from human and other applications' perspectives. Although BYTEA has a hex format, so that's probably equivalent
3. Like you said BYTEA can't be fixed sized (actually I think there are hacky workarounds like https://stackoverflow.com/questions/35532100/can-i-set-within-the-dbase-a-size-limit-on-a-bytea-field-in-postgresql). VARCHAR(66) is the num of characters required to store the "0x" prefixed hex string (32 bytes, 64 hex chars + 2 chars for "0x") for a 32 byte hash (and also fits address which is 20 bytes but if we wanted to me more precise we would define those columns as VARCHAR(42).

2023-03-08 18:02 UTC, i-norden commented
Merging this with the fixes you mentioned, but there will be another coming in shortly with some follow up fixes for issues discovered while adding another unit test.

2023-03-08 18:02 UTC, merged

2023-03-09 09:10 UTC, roysc commented on db/migrations/00017_create_get_storage_at_functions.sql
> +                AND state_cids.block_number = header_cids.block_number
Right, we can touch this by just searching for a nonexistent node